---
blank_issues_enabled: false
contact_links:
  - name: "📕 Documentation Issue"
    url: https://help.branch.io/developers-hub/docs/capacitor
    about: Report an issue in the Branch Capacitor SDK Reference documentation by clicking "Suggest edits" button on the documentation page.
  - name: "Branch Support"
    url: https://help.branch.io/using-branch/page/submit-a-ticket
    about: If you are having general trouble with Branch Capacitor SDK integration, please submit a ticket to Branch Support.
